GAME_LIST: "gameListPS_0.json"
GAME_DISSCOUNTS: "game_list_discounts.json"
GAME_SOURCE: "store.playstation.com"
GAME_PREFIX: "PS_"
GAME_BUNDLE: 3

BASE_URL_PS: "https://store.playstation.com"
BASE_URL_SALES_PS: "https://store.playstation.com/ru-ru/grid/STORE-MSF75508-PRICEDROPSCHI/"
BASE_URL_SALES_PARAM: "?gameContentType=games"

PROXY_HOST: "grsst.s5.opennetwork.cc"
PROXY_PORT: 999
PROXY_USER: "707869746"
PROXY_PASSWORD: "TSDqvatE"

BOT_KEY: "1043462173:AAGVqh6R0Nk0-kW0mQAX5k8JiT8Rib-OY7g"

CHANNEL_NAME: "@game_demo_ps"

LOG_WARN: "logs.log"